import { useState, useMemo } from 'react';
import { BookOpen, Settings } from 'lucide-react';
import ConfigModal from './ConfigModal';
import authStore from '@/stores/public/auth-store';
import { useGetQuestionConfigs, useUpdateQuestionConfig } from '@/queries/admin/useQuestion';
import { Skeleton } from '@/components/ui/skeleton';
import { useQueryClient } from '@tanstack/react-query';

const INTERVIEW_TYPE_DETAILS = [
  {
    type: 'Basic',
    description:
      'Basic is a practice for answering simple, introductory questions where follow-up questions are tailored to your self-introduction and responses. Follow-up questions are generated by AI.',
  },
  {
    type: 'Expert',
    description:
      'Expert is an advanced practice with job-specific questions generated by AI based on their desired job title and resume.',
  },
];
export default function BasicAndExpert() {
  const queryClient = useQueryClient();
  const user = authStore((state) => state.user);
  const { data: questionConfig = [], isPending } = useGetQuestionConfigs(user!);
  const [isShowConfig, setIsShowConfig] = useState<'Basic' | 'Expert' | null>(null);

  const { mutate: updateQuestionConfig, isPending: isUpdating } = useUpdateQuestionConfig({
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['question-config'] });
      setIsShowConfig(null);
    },
  });
  const interview = useMemo(() => {
    return questionConfig.map((config) => {
      const item = INTERVIEW_TYPE_DETAILS.find(
        (item) => item.type.toUpperCase() === config.type.toUpperCase()
      );
      return {
        ...config,
        type: item!.type,
        description: item!.description,
      };
    });
  }, [questionConfig]);

  return (
    <div className="grid gap-2">
      {isPending ? (
        <>
          <Skeleton className="mt-2 h-5 w-3/4" />
          <div className="grid gap-4 sm:grid-cols-1 md:grid-cols-2">
            {INTERVIEW_TYPE_DETAILS.map((item) => (
              <div
                key={item.type}
                className="overflow-hidden rounded-xl border border-gray-200 bg-white p-4"
              >
                <div className="flex h-full flex-col justify-between gap-4">
                  <div>
                    <div className="mb-3 flex items-center gap-3">
                      <Skeleton className="h-10 w-10 rounded-full" />
                      <Skeleton className="h-6 w-48" />
                    </div>
                    <Skeleton className="mb-2 h-4 w-full" />
                    <Skeleton className="mb-2 h-4 w-full" />
                    <Skeleton className="h-4 w-3/4" />
                  </div>

                  <div className="mt-4">
                    <Skeleton className="h-9 w-32 rounded-lg" />
                  </div>
                </div>
              </div>
            ))}
          </div>
        </>
      ) : (
        <>
          <p className="mt-2 text-gray-600">
            Customize the number of questions generated for each interview type.
          </p>

          <div className="grid gap-4 sm:grid-cols-1 md:grid-cols-2">
            {interview.map((item) => {
              return (
                <>
                  <div
                    key={item.type}
                    id={item.type}
                    className="group relative overflow-hidden rounded-xl border border-gray-200 bg-white p-4"
                  >
                    <div className="flex h-full flex-col justify-between gap-4">
                      <div>
                        <div className="mb-3 flex items-center gap-3">
                          <div className="flex h-10 w-10 items-center justify-center rounded-full bg-green-100 text-green-600">
                            <BookOpen size={20} />
                          </div>
                          <h3 className="text-lg font-semibold text-gray-900">{`${item.type} Interview Questions`}</h3>
                        </div>
                        <p className="mb-4 text-sm leading-relaxed text-gray-600">
                          {item.description}
                        </p>
                      </div>

                      <div className="mt-4 space-y-4">
                        <button
                          className="flex items-center gap-2 rounded-lg bg-green-50 px-4 py-2 text-sm font-medium text-green-700 transition-colors hover:bg-green-100"
                          onClick={() => setIsShowConfig(item.type as 'Basic' | 'Expert')}
                        >
                          <Settings size={16} />
                          Configure
                        </button>
                      </div>
                    </div>
                  </div>
                  {isShowConfig === item.type && (
                    <ConfigModal
                      category={`${item.type} Interview`}
                      onClose={() => setIsShowConfig(null)}
                      initialValue={item.numberOfQuestionToGenerate}
                      onSave={(value) =>
                        updateQuestionConfig({ id: item._id!, numberOfQuestionToGenerate: value })
                      }
                      isLoading={isUpdating}
                    />
                  )}
                </>
              );
            })}
          </div>
        </>
      )}
    </div>
  );
}
