import { useState } from 'react';
import { BookOpen, Settings, Trophy } from 'lucide-react';
import ConfigModal from './ConfigModal';

const initialInterviewType = [
  {
    type: 'Basic',
    description:
      'Basic is a practice for answering simple, introductory questions where follow-up questions are tailored to your self-introduction and responses. Follow-up questions are generated by AI.',
    numberOfQuestionToGenerate: 5,
  },
  {
    type: 'Expert',
    description:
      'Expert is an advanced practice with job-specific questions generated by AI based on their desired job title and resume.',
    numberOfQuestionToGenerate: 5,
  },
];

export default function BasicAndExpert() {
  const [isShowConfig, setIsShowConfig] = useState(false);

  return (
    <div className="grid gap-2">
      <p className="mt-2 text-gray-600">
        Customize the number of questions generated for each interview type.
      </p>

      <div className="grid gap-4 sm:grid-cols-1 md:grid-cols-2">
        {initialInterviewType.map((item, index) => {
          return (
            <>
              <div
                key={item.type}
                className="group relative overflow-hidden rounded-xl border border-gray-200 bg-white p-4"
              >
                <div className="flex h-full flex-col justify-between gap-4">
                  <div>
                    <div className="mb-3 flex items-center gap-3">
                      <div className="flex h-10 w-10 items-center justify-center rounded-full bg-green-100 text-green-600">
                        <BookOpen size={20} />
                      </div>
                      <h3 className="text-lg font-semibold text-gray-900">{`${item.type} Interview Questions`}</h3>
                    </div>
                    <p className="mb-4 text-sm leading-relaxed text-gray-600">{item.description}</p>
                  </div>

                  <div className="mt-4 space-y-4">
                    <button
                      className="flex items-center gap-2 rounded-lg bg-green-50 px-4 py-2 text-sm font-medium text-green-700 transition-colors hover:bg-green-100"
                      onClick={() => setIsShowConfig(true)}
                    >
                      <Settings size={16} />
                      Configure
                    </button>
                  </div>
                </div>
              </div>
              {isShowConfig && (
                <ConfigModal
                  category={`${item.type} Interview`}
                  onClose={() => setIsShowConfig(false)}
                  initialValue={item.numberOfQuestionToGenerate}
                />
              )}
            </>
          );
        })}
      </div>
    </div>
  );
}
